In [3]:
import tkinter as tk
import numpy as np
from tkinter import filedialog
from tkinter.filedialog import askopenfile
from PIL import Image, ImageTk
from keras.models import load_model
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
from tensorflow.keras.preprocessing import image
import numpy as np

In [3]:
my_w = tk.Tk()
my_w.geometry("1280x720")
my_font1=("Helvacita", 18, 'bold')
l1 = tk.Label(my_w,text='Add Lung Image',height=10,width=80,font=my_font1)  
l1.grid(row=1,column=1)
b1 = tk.Button(my_w, text='Upload File',  width=20,command = lambda:upload_file())
b1.grid(row=2,column=1) 
def upload_file():
    global img
    f_types = [('Jpg Files', '*.jpg'),("JPEG Files" ,"*.jpeg"),("PNG images","*.png")]
    filename = filedialog.askopenfilename(filetypes=f_types)
    img = ImageTk.PhotoImage(file=filename)
    img = ImageTk.PhotoImage(Image.open(filename))
    print(filename)
    model=load_model('D:/Hack/model_vgg16.h5')
    img=image.load_img(filename,target_size=(224,224))
    x=image.img_to_array(img)
    x=np.expand_dims(x,axis=0)
    img_data=preprocess_input(x)
    classes=model.predict(img_data,verbose='None')
    print(classes)
    lis=classes.tolist()
    print(lis)
    if lis==[[0.0,1.0]]:
        print("Pneumonia")
        a=tk.Label(my_w,text="Paitent Report\nPneumonia")
        a.grid(columnspan = 3,column=0,row=3)
    else:
        print("Normal")
        a=tk.Label(my_w,text="Paitent Report\nNormal")
        a.grid(columnspan = 3,column=0,row=3)
    c1 = tk.Button(my_w, text='Clear screen',  width=20, command = lambda:a.config(text=" "))
    c1.grid(row=7,column=1)
        
my_w.mainloop()

D:/Hack/lung/test/PNEUMONIA/person1_virus_13.jpeg
1/1 [==============================] - 0s 252ms/step
[[0. 1.]]
[[0.0, 1.0]]
Pneumonia
D:/Hack/lung/test/NORMAL/IM-0007-0001.jpeg
1/1 [==============================] - 0s 223ms/step
[[9.9954838e-01 4.5157073e-04]]
[[0.9995483756065369, 0.00045157072599977255]]
Normal


In [4]:
my_w = tk.Tk()
my_w.geometry("1280x720") 
my_font1=("Helvacita", 18, 'bold')
l1 = tk.Label(my_w,text='Add skin Image',height=10,width=80,font=my_font1)  
l1.grid(row=1,column=1)
b1 = tk.Button(my_w, text='Upload File',  width=20,command = lambda:upload_file())
b1.grid(row=2,column=1) 
def upload_file():
    global img
    f_types = [('Jpg Files', '*.jpg'),("JPEG Files" ,"*.jpeg"),("PNG images","*.png")]
    filename = filedialog.askopenfilename(filetypes=f_types)
    img = ImageTk.PhotoImage(file=filename)
    img = ImageTk.PhotoImage(Image.open(filename))
    print(filename)
    model=load_model('D:/Hack/skin_Cancer20epochs.h5')
    pred_image = image.load_img(filename,target_size=(224, 224))
    pred_image = image.img_to_array(pred_image)
    pred_image = np.expand_dims(pred_image,axis = 0)
    answer = model.predict(pred_image,verbose='None')
    print(answer)
    if answer[0][0] < 0.1:
        a=tk.Label(my_w,text="Paitent Report\nBENIGN skin cancer")
        a.grid(columnspan = 3,column=0,row=3)
    else:
        a=tk.Label(my_w,text="Paitent Report\nMALIGNANT skin cancer")
        a.grid(columnspan = 3,column=0,row=3)
    c1 = tk.Button(my_w, text='Clear screen',  width=20, command = lambda:a.config(text=" "))
    c1.grid(row=7,column=1)
        
my_w.mainloop()

D:/Hack/archive/test/benign/5.jpg
[[4.6061173e-15 9.9999952e-01 4.7364193e-07]]


In [31]:
import speech_recognition as sr
import openai
import pyttsx3    
engine = pyttsx3.init()  

openai.api_key = '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' 

recognizer = sr.Recognizer()

def process_speech_input(audio):
    try:
        text = recognizer.recognize_google(audio)
        print("You said:", text)

        # Pass the speech input to ChatGPT and get the model's response
        model_response = chat_with_gpt(text)

        # Print the model's reply
        print("ChatGPT:", model_response)
        engine.say(model_response) 
        engine.runAndWait()  

        # Perform further processing or actions with the model_response if needed
        # ...

    except sr.UnknownValueError:
        print("Could not understand audio")
    except sr.RequestError as e:
        print("Error: {0}".format(e))

# Function to interact with ChatGPT and get its response
def chat_with_gpt(message):
    # Make an API call to ChatGPT
    response = openai.Completion.create(
        engine='text-davinci-003',  # Replace with your desired ChatGPT model
        prompt=message,
        max_tokens=50,
        temperature=0.7
    )

    # Extract and return the generated response from ChatGPT
    return response.choices[0].text.strip()

# Use the default microphone as the audio source
with sr.Microphone() as source:
    print("Listening...")


    # Listen for user input
    audio = recognizer.listen(source)

    # Process the speech input
    process_speech_input(audio)

Listening...
You said: 10 sentences
ChatGPT: 1. I always get up early to start my day off right.
2. I like to take a walk in the morning to get my body and mind going.
3. I usually have a healthy breakfast to fuel my day.
